const fs   = require('fs');
const path = require('path');
const logger = require('./logger');

/**
 * Groups compiled plugins by plugins_ini_postfix and writes .ini files
 * into build/configs/.
 *
 * Returns an array of { iniPath, iniName, count } for logging.
 */
function buildIniFiles(compiledPlugins, manifest, buildDir) {
  const configsDir = path.join(buildDir, 'configs');
  fs.mkdirSync(configsDir, { recursive: true });

  // Group by postfix
  const groups = new Map(); // postfix → [{ repoName, ref, amxxName, ini_comment }]

  for (const plugin of compiledPlugins) {
    const postfix = plugin.plugins_ini_postfix;
    if (!groups.has(postfix)) groups.set(postfix, []);
    groups.get(postfix).push(plugin);
  }

  const result = [];

  for (const [postfix, plugins] of groups) {
    const iniName = postfix ? `plugins-${postfix}.ini` : 'plugins.ini';
    const iniPath = path.join(configsDir, iniName);

    const lines = ['; Generated by amxx-builder'];

    // Group by source repo for comments
    let lastRepo = null;
    for (const plugin of plugins) {
      const repoId = `${plugin.repo} @ ${plugin.ref}`;
      if (repoId !== lastRepo) {
        lines.push('');
        lines.push(`; Source: ${repoId}`);
        lastRepo = repoId;
      }
      const comment = plugin.ini_comment ? `\t; ${plugin.ini_comment}` : '';
      lines.push(`${plugin.amxxName}${comment}`);
    }
    lines.push('');

    fs.writeFileSync(iniPath, lines.join('\n'), 'utf8');
    logger.info(`Generated: ${iniName} (${plugins.length} ${plugins.length === 1 ? 'entry' : 'entries'})`);

    result.push({ iniPath, iniName, count: plugins.length });
  }

  return result;
}

module.exports = { buildIniFiles };
