const fs   = require('fs');
const path = require('path');
const logger = require('./logger');

/**
 * Groups compiled plugins by plugins_ini_postfix and writes .ini files
 * into build/amxmodx/configs/.
 */
function buildIniFiles(compiledPlugins, buildDir) {
  if (!compiledPlugins.length) return;

  const configsDir = path.join(buildDir, 'amxmodx', 'configs');
  fs.mkdirSync(configsDir, { recursive: true });

  const groups = new Map(); // postfix → [plugin]
  for (const plugin of compiledPlugins) {
    const k = plugin.plugins_ini_postfix;
    if (!groups.has(k)) groups.set(k, []);
    groups.get(k).push(plugin);
  }

  for (const [postfix, plugins] of groups) {
    const iniName = postfix ? `plugins-${postfix}.ini` : 'plugins.ini';
    const iniPath = path.join(configsDir, iniName);

    const lines = ['; Generated by amxx-builder'];
    let lastRepo = null;
    for (const p of plugins) {
      const repoId = `${p.repo} @ ${p.ref}`;
      if (repoId !== lastRepo) {
        lines.push('', `; Source: ${repoId}`);
        lastRepo = repoId;
      }
      const comment = p.ini_comment ? `\t; ${p.ini_comment}` : '';
      lines.push(`${p.amxxName}${comment}`);
    }
    lines.push('');

    fs.writeFileSync(iniPath, lines.join('\n'), 'utf8');
    logger.info(`Generated: ${iniName} (${plugins.length} ${plugins.length === 1 ? 'entry' : 'entries'})`);
  }
}

module.exports = { buildIniFiles };
